### ISSUE TITLE
I can't save output video as a new file

### ISSUE THREAD

**Issue by tripletopper** [gkv311/sview#19] opened 2016-12-06 04:10 UTC
I can successfully load a 3DS video and display it as a red and cyan image in accurate 3D.   2 questions.

1.  Can this device convert a 480p x 240p x 20f x 2e to a side by side half width video that I can burn on a DVD and display in it's proper stereo vision on a 3D TV with a manual side by side mode?   I can't tell if side by side mode is compatible with 3D TV in manual mode.   (I believe it needs half widths to do it right.)

2.  Once converted, can I save either a Red and Cyan or a Side By Side half view as a separate avi or mp4 files that can be edited in a 2D video viewer and editor.   I understand I can't manipulate the 3D once I make the transition.   It's a wysiwyg 3D, meaning I can't have a Godzilla vs. Radioactive Lebron James battle in the skyline of Akron.  If I film a miniature golf game in 3D at a 1:1 real human scale, it will look like a miniature golf course at a 1:1 real human scale.  I need to edit it down in iMovie and add titles.

I'd be willing to pay $10 for this feature if a) you can make what I said happen, and b) become an Apple recognized author so I don't have to backdoor the DMG.

Brian
tripletopper@earthlink.net

**Comment by gkv311** [comment] 2016-12-06 05:56
Hello Brian,

sView is a viewer/player, not a video recorder / editor / conversion tool.

It is better considering specialized tools for this kind of operations like ffmpeg (command line tool) or editor with convenient and function user interface for this purpose. Though I don't use any such tool, I believe modern editor software should provide necessary functionality for processing stereoscopic pairs (at least command line ffmpeg tool provides several built-in video filters for converting stereoscopic pairs).

> become an Apple recognized author so I don't have to backdoor the DMG.
I don't have any interest paying Apple USD 100 annually
(as well as more annual fees for singing certificates for Windows platform):
https://developer.apple.com/support/purchase-activation/

**Comment by tripletopper** [comment] 2016-12-06 18:01
I respect your decision not to be an Apple authorized dealer.   I just brought it up wondering if it was an intentional choice or an oversight.   I see it's an intentional choice.

As for the video.  I would use a 3D converter from a different company, but NONE of the ones I've seen are able to accurately convert Nintendo 3DS video.   But your product can display Nintendo 3DS 3D video correctly.   Those  3D converters don't understand the 2 separate left eye and right eye streams in one file.   All other 3D converters don't see the 2 separate streams as l/r.  It just sees one file and thinks it's a monoscopic file.

Yours is the only player that can play 3DS videos correctly but it currently can't transcode the video into side-by-side half or red and cyan AND save the file as a video file.   I have a Macintosh OS 10.12 and would want a tool that can do stereoscopic 3D right so I can transfer it to iMovie.  I understand once I convert from a native 3D format to a split eyer format, that frames are stored as wholes and the 3D depth factors cannot be manipulated once the 3D is converted from l/r to R+C or SBSH as the computer thinks of it as 2D video encoded with 3D info.

I would pay more than $10 because the other 3D video converters don't understand synched dual stream AVI.  The only one that does is Final Cut Pro and it's ridiculous to pay $300 just to have that dual eye transfer feature.  Any alternatives would be nice.   If you added a video converter for sale I'd pay $20, plus since you're not paying for apple athorization, you could keep more of that, compared to $40 for an Apple Authorized program maker.

Finally there is a difference in being in the Apple Store and being an Apple authorized DMG autor.  The apple authorized DMG is probably cheaper than being in the Apple store.   But the way you're doing it now is the cheapest.   And thanks for telling me how to load unauthorized DMGs .)

**Comment by gkv311** [comment] 2016-12-06 18:55
> Finally there is a difference in being in the Apple Store and being an Apple authorized DMG autor. The apple authorized DMG is probably cheaper than being in the Apple store

As far as I understand, to be in Apple store you need to prolong developer program each year (just to keep already published program there). But signed DMG will work longer (although I'm not sure yet if I will be able to sign new DMG next year with existing key, or I'll have to prolong the Developer Program).

Anyway, I have evaluated signing question for different platforms some time ago, and it does not sound reasonable for small open-source projects.

Small overview:
- **Linux** (e.g. Launchpad / other repository for Debian packages).
  You create a sing certificate and ask users to install public key as trusted.
  _**User decides**_ which certificates are trusted (distributes come with pre-installed trusted keys to their upgrade/install packages servers). It is up to developer to decide how long certificate is valid (too short lifetime will require user to load new public key). Package is signed, not application binaries themselves.
- **Android**.
   _**One-time**_ $25 fee.
  User might install unsigned / self-signed applications on device with disabled check options.
  Signing is required for publishing onto Google Play.
  Certificate is created once (in fact it should be valid during entire application lifetime - e.g. many years - otherwise developer will be unable to provide an application update) and pushed to Google Play for developer identification. Package is signed, not binaries themselves.
- **Web / https** (SSL).
  You buy a singing certificate derived from one of trusted root signed centers ($75+ _**per year**_ or free certificates from Let’s Encrypt or similar services).
  **_Browser_** (Firefox / Chrome / IE) decides which root certificate centers to trust (user might local accept own-signed certificates). Site webmaster has to prolong certificate regularly.
  User may accept self-signed certificates (big warning with clear message shown) and register them as trusted locally.
- **OS X / iOS** for App Store.
  Developer should buy _**annual Developer Program**_ ($100+) to publish application on App Store and keep it there. Originally, developer have to by two different Developer programs - for iOS and for OS X (they have been merged a year ago).
  **_Apple decides_** which certificates are trusted (and actually only Apple server can generate valid private keys for signing). Application binaries are signed (and, probably, package as well).
  User (and even Developer) is unable installing unsigned application onto iOS device.
  User is able installing unsigned application onto OS X, however procedure is not trivial - user need to navigate to application in Finder (Launchpad does not work) and start application with Shift key - to unlock button to start application. Already signed DMG files are still valid (distributes independently), but not for AppStore.
- **Windows** (excluding Windows Store - I don't have much details for this platform).
  Scheme is similar to Web / https (SSL) and trusted centers are similar. But developer has to buy extra certificate for signing Windows binaries ($170+ **_per year_** without discounts). Certificate centers are trying to make a business by suggesting certificates of different "quality" (developer identification information) - Internet Explorer (and some antiviruses) shows hostile warnings (with hidden action buttons) even for signed application - if it is not an EV (extended validation) certificate ($450+ per year without discounts).
  Binaries are signed (and installation package, since it is usually binary as well). Already signed binaries remain valid.
  **_Microsoft_** decides which root certificate centers should be trusted. User is able installing unsigned application with clear warning message. There are, however, more restrictions for drivers developers. Also domain administrators are able pre-installing self-signed certificates onto domain workstations. Technically, user might install certificates (public keys) by their own from developer site (like in case of Linux), but it is not straightforward and nobody uses such practice.

**Comment by tripletopper** [comment] 2016-12-06 22:30
I never got my answer on how I convert a "2 stream 1 file" file into side by side half or red and cyan. and have it burnable on DVD or downloadable to youtube.

Most 3D converter programs don't understand "2 streams 1 file" files, and iMovie, the basic movie editor, can't distort pictures for side by side half.

I understand if I want HD I need a Blu Ray, but standard definition 3D should be burnable on DVD when used with a 3dtv in "side-by-side half" mode if the DVD played in an HDMI based DVD player, OR Make a 20 minute Blu Ray using Blu Ray language on a DVD physical disc.

The above was the main question I wanted to ask.  The rest is addressing the thing you focued on.

And about the certificates, I feel your pain. The new version of Java requires a new signature, and I don't know how to add one.   Basically I hired someone to program a game, and lost contact with him 15 years ago, and his authorized friend/partner last year.   So now I'm stuck with an online game with no way to run it today.  it was programmed in Java 1.2

And about  the DMGs, would scanning the DMGs for viruses and other naughties ensure a safe, even though it's not "authorized", application in terms of malware, spyware and viruses?

**Comment by tripletopper** [comment] 2016-12-07 19:12
Most stereoscopic format converters don't know how to deal with Nintendo 3DS video.   Yours can, but I can't save its results of playback.   Is there an option that can somehow save the video playback as a file?   Any options? I've got Macintosh OS 10.12  And no, Final Cut Pro is too expensive and expansive, containing features I don't need and paying for them.

**Comment by tripletopper** [comment] 2016-12-07 19:14
I'm looking to save it as both a red and cyan file and a separate side-by-side half format for  3D broadcasts.  Your program converts it almost instantaneously.  But I can't use its results for video production.

**Comment by tripletopper** [comment] 2016-12-07 19:22
I looked up the program you recommended, ffmpeg, and A) I don't know how to use command line, and 2, the directions have too amny temrs I don't uinderstand.  It feels like reading a foreign language.   I want to take stereoscopic 3DS file x.avi and convert it to ANY mac acceptable file forma encoded in either red and cyan and/or side-by-side half.   Once I get it converted, I can then edit as I see fit.

**Comment by gkv311** [comment] 2016-12-08 08:15
Hello Brian,

you don't need to duplicate your messages here - I have read them and understand your position.
I just don't know how to help you - I'm not an expert in video recording / conversion.

What are you looking for - is a tool with a single button "save the video".
But the problem is that video encoding and muxing is not so simple - ffmpeg tool has a plenty of command line arguments for a reason.

The software without options will be nearly useless, because everybody is looking for different result. The minimal options would be target container (AVI / MKV / WEBM...), video encoder (VP8 / VP9 / FFV1 / Huffyuv / MJPEG....), audio encoder, video resolution (scaling), stereoscopic format (dual stream, side by side, over/under, matrix of anaglyph options,...), video filters, video profile / compatibility (plenty of them - you need to know which profiles are supported by target devices or other software tools), video encoding quality / compression ratio (each of video codec has _different_ options affecting result quality and encoding speed), pixel format conversion, handling multiple video / audio streams, handling subtitles, handling metadata, handling language marks.

Of course, in simplest case application might not provide all options actually affecting result (anyway, most users will not need them all or will not be able using them), but this still does not mean that application might don't care about them at all - result might just not satisfy user, and the major options should be still defined somehow.

Apart from the application code that should be written for actually performing conversion (of course, based on already used FFmpeg framework), the user interface should be also extended and progress indicator should be introduced (ideally showing intermediate frame).

This does not mean that video encoding/muxing will never appear in sView - but it is certainly not a core functionality for viewing / playing application, and there is no expected timeline when I will be able to work on this functionality / will have a good mood for this.

**Closed** 2018-09-26 05:53 UTC
Labels: enhancement, wontfix
