### ISSUE TITLE
Compilation failures  with "undefined reference to `vtable for __cxxabiv1::__class_type_info'"

### ISSUE THREAD

**Issue by dikonov** [gkv311/sview#42] opened 2018-12-15 12:20 UTC
The master branch as of 15 dec 2018 fails to compile with the folowing errors:

```
/usr/bin/ld.default: /home/slava/RPM/BUILD/sview-master/StShared/stConsole.o:stConsole.cpp:(.text+0x181): more undefined references to `std::basic_ostream<char, std::char_traits<char> >& std::__ostream_insert<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*, long)' follow
/usr/bin/ld.default: /home/slava/RPM/BUILD/sview-master/StShared/stConsole.o: in function `_GLOBAL__sub_I_stConsole.cpp':
stConsole.cpp:(.text.startup+0xc): undefined reference to `std::ios_base::Init::Init()'
/usr/bin/ld.default: stConsole.cpp:(.text.startup+0x13): undefined reference to `std::ios_base::Init::~Init()'
/usr/bin/ld.default: /home/slava/RPM/BUILD/sview-master/StShared/stUtfTools.o: in function `_GLOBAL__sub_I_stUtfTools.cpp':
stUtfTools.cpp:(.text.startup+0xc): undefined reference to `std::ios_base::Init::Init()'
/usr/bin/ld.default: stUtfTools.cpp:(.text.startup+0x13): undefined reference to `std::ios_base::Init::~Init()'
/usr/bin/ld.default: /home/slava/RPM/BUILD/sview-master/StShared/StGLResource.o: in function `StGLResource::~StGLResource()':
StGLResource.cpp:(.text+0x1e): undefined reference to `operator delete(void*)'
/usr/bin/ld.default: /home/slava/RPM/BUILD/sview-master/StShared/StGLResource.o:(.data.rel.ro._ZTI12StGLResource[_ZTI12StGLResource]+0x0): undefined reference to `vtable for __cxxabiv1::__class_type_info'
/usr/bin/ld.default: /home/slava/RPM/BUILD/sview-master/StShared/StGLResource.o:(.data.rel.ro._ZTV12StGLResource[_ZTV12StGLResource]+0x20): undefined reference to `__cxa_pure_virtual'
collect2: error: ld returned 1 exit status
make: *** [Makefile:338: libStShared.so] Ошибка 1

```
$ g++ --version
g++ (GCC) 8.2.1 20181011 (ALT Sisyphus 8.2.1-alt1)
Copyright (C) 2018 Free Software Foundation, Inc.

Compilation of other sources, e.g. bino works...

**Comment by gkv311** [comment] 2018-12-17 20:04
I'm unable reproducing the issue.
- Downloaded Xfce/x86_64 from
  https://en.altlinux.org/Regular
- Installed development packages
  `apt-get install gcc8-c++ gcc-c++ libGLU-devel libgtk+2-devel libXrandr-devel libfreetype-devel libopenal-devel libconfig-devel libconfig-c++-devel libXpm-devel libwebp-devel libavcodec-devel libavdevice-devel libavformat-devel libavutil-devel libswscale-devel git-gui gitk`
```
[kirill@comp-core-i5-7300hq-1ae184 build]$ g++ --version
x86_64-alt-linux-g++ (GCC) 8.2.1 20181011 (ALT Sisyphus 8.2.1-alt1)
```
- Cloned sView repository
```
  mkdir develop
  cd develop
  git clone https://github.com/gkv311/sview.git sview.git
  cd sview.git
```
- Build sView
```
  make clean
  make -j4
```

Building has finished without errors.
Although I'm unable to start any OpenGL application within VirtualBox due to broken OpenGL drivers in ALT Linux.

Are there some differences from yours scenario?

**Comment by gkv311** [comment] 2018-12-26 18:50
I have also tried i586 system image - there was an issue with GLsizeiptr typedef conflict (correction has been pushed to master), but no errors similar to description in the original post.

I'm closing this issue - fill free to reopen it if problem is still reproducible on your side, but please provide more information for reproducing.

**Closed by gkv311** 2018-12-26 18:50 UTC
