### ISSUE TITLE
Complaining about missing OpenGL 2.0 on a system which reports it has OpenGL 2.0

### ISSUE THREAD

**Issue by secarica** [gkv311/sview#37] opened 2018-03-31 09:43 UTC
On a laptop with ATI Mobility Radeon X1600, running MS Windows 8.1, the OpenGL Extensions Viewer utility shows a valid OpenGL 2.0 [1]. However, sView won't start because "OpenGL 2.0 is required by Anaglyph Output" / "OpenGL 2.0 is required by Image Viewer!”

What's the mystery ?

[1] http://www.secarica.ro/misc/opengl_report_radeon_x1600.png

**Comment by gkv311** [comment] 2018-04-12 07:46
This message is generated by the following lines of code:
>     if(!myContext->isGlGreaterEqual(2, 0)) {
>        myMsgQueue->pushError(stCString("OpenGL 2.0 is required by Anaglyph Output"));

So, it is indeed, strange if driver really supports OpenGL 2.0.
StGLContext::stglInit() validates not only version but also a presence of all functions required by specs,
so that I suppose that either some function is missing, or there is an error in validation routine.
Though this would be very strange, since this code has been tested on many platforms for many years.

I may prepare a verbose build of sView for determining a place, where problem occurs, if you are willing to help.
Could you please also share the information about AMD driver version installed for your Radeon card?
And is it 32-bit or 64-bit system?

**Comment by gkv311** [comment] 2018-09-26 05:47
Closed as not enough info to reproduce.

**Closed by gkv311** 2018-09-26 05:47 UTC
Labels: question
